### ISSUE TITLE
Server size is being configured incorrectly, causing backups not to run

### ISSUE THREAD

**Issue by katmoody** [humanmade/backupwordpress#1063]
Per conversation with @pdewouters - since changing up the function and displaying an error message when the plugin sees the server doesn't have enough space, users are basically getting false positives. Not sure if the function needs rewritten for that or taken out. Might need further information but wanted to list it while we were thinking about it.

**Comment by willmot** [comment]
This should be fixed in https://github.com/humanmade/backupwordpress/pull/1052 which should go out in the 3.6.1 release.

**Comment by katmoody** [comment]
While this seems to fix the issue for most users, we're still getting some folks with false positives. 

from wp.org forum post: https://wordpress.org/support/topic/our-server-only-has-blank-of-disk-space-left?replies=9

**Comment by katmoody** [comment]
From one user: 

> ### WordPress Environment ###
> 
> WP Version: 4.5.2
> WP Multisite: –
> WP Memory Limit: 256 MB
> Language: ru_RU
> 
> ### Server Environment ###
> 
> Server Info: Apache/2.4.7 (Ubuntu)
> PHP Version: 5.5.9-1ubuntu4.11
> PHP Post Max Size: 8 MB
> PHP Time Limit: 0
> PHP Max Input Vars: 1000
> SUHOSIN Installed: –
> MySQL Version: 5.5.44
> Max Upload Size: 8 MB
> Default Timezone is UTC: ✔
> fsockopen/cURL: ✔
> SoapClient: ✔
> DOMDocument: ✔
> GZip: ✔
> Multibyte String: ✔
> 
> BackUpWordPress: от Human Made Limited – 3.6.1

**Comment by mrhistalk** [comment]
I originally had an actual disk space problem caused by having multiple copies of the large weekly backup that seemed to suddenly swell to 135gb per copy. I deleted those files to free up space, but the Tools/Backup panel still wouldn't display anything more than the message that I didn't have enough space free (even though at that point I had plenty of space free -- 485GB at the moment).

This morning I went back into Tools/Backups and it brought up a list of daily backups instead of the error message, so that worked correctly. I then clicked the Weekly tab and again got the "not enough disk space" message. That now happens each time I exit and return to Tools/Backups.

**Comment by sanya-kuzovlev** [comment]
@katmoody I can provide temporary admin access to your website, if it helps to solve the problem.

**Comment by willmot** [comment]
@sanya-kuzovlev that would be really helpful, could you send to tom@humanmade.co.uk. Thanks!

**Comment by katmoody** [comment]
@willmot was there any followup after being able to check out the last site? I have other complaints about this one and not positive what else we can check?

**Comment by willmot** [comment]
I never actually received access details. @sanya-kuzovlev are you still able to provide access to your site?

**Comment by willmot** [comment]
in https://github.com/humanmade/backupwordpress/issues/1084 it looks like some who are seeing this error don't actually have a calculated site size, so that's at least an avenue to test against.

**Comment by willmot** [comment]
@katmoody have we had any other reports of this one happening. I _think_ we should have covered all edge-cases off in the last couple of minor releases.

**Comment by katmoody** [comment]
I don't think I have new cases of this happening. I'll revisit if I see any come in.

**Comment by willmot** [comment]
Great! going to close in the meantime, but re-open if anything pops up!

**Comment by willmot** [comment]
Looks like this is still happening

**Comment by dashaluna** [comment]
@willmot any more information on this? Not sure how to start testing this.

**Comment by katmoody** [comment]
I just got a new ticket on that and working through other troubleshooting - if that fails I will ask for server access or ask them to check specific things if they are wary about that - what should I be asking for them to check specifically? What might cause this to be happening?

**Comment by dashaluna** [comment]
@katmoody do you know exact wording for the error message? It'll help to find a starting place in code to investigate that further :)d

**Comment by katmoody** [comment]
Hey @dashaluna - exact error: 
>Your server only has 112 GB of disk space left which probably isn't enough to complete a backup. Try deleting some existing backups or other files to free up space.

**Comment by bk1285** [comment]
Same thing here: 

>     Your server only has 14 GB of disk space left which probably isn't enough to complete a backup. Try deleting some existing backups or other files to free up space.

Deleting some backups results in 14.5 GB of free diskspace, which allows me to schedule backups again. ... until I reach 14 GB again.

**Comment by katmoody** [comment]
Hey @bk1285 - thanks for weighing in on this - are you able to tell us anything else about your server setup? Are you on shared hosting? Does the host limit how many files are able to be on a given plan or anything at all like that? I'm beginning to wonder if there's an internal server thing interfering with this somewhere? 

Not sure what that would be though?

**Comment by bk1285** [comment]
I'm on a MS azure server, running ubuntu. No shared hosting, no limit on any files (to the best of my knowledge)

**Comment by bk1285** [comment]
Hi there!
Some further details:
disk_space_low is called with backup_size=0.
Then the backup-size is calculated relying on $backup_size = $site_size->get_site_size() * 2; 
Result: 7.2GB * 2 = 14.4GB space required. 
Since only 14GB are available, the math is obviously correct. The site_size is however quite huge?? The finally resulting backup-sizes are around 800MB (Not 7.2 GB!)

Regards,
Bernd

**Comment by bk1285** [comment]
To calculate the expected backup-size, the directories, which are excluded from backup, are considered as well. Considering this, I'd really need something like 14GB.
There excluded directories hold git-repositories, the backupwordpress-folder itsself, and so on...: Stuff, I acutally don't need in my backup... ;)
I think, if you don't consider this while calculating the expected backup-size, everything should be fine again? Hope that helps?
Regards, Bernd

**Comment by katmoody** [comment]
Thank you so much for the very helpful notes @bk1285 - that will definitely help as the developers dig into this more fully - we really appreciate your help and input!

**Comment by katmoody** [comment]
Just got a new ticket with this - This guy has an apparent 177GB of space left on his server ... and his complete backup is only 162MB ... let me know if you want further info or need me to find specific information from the ticket, okay?

**Comment by katmoody** [comment]
@dashaluna - I'm removing the 'infrequent' label as I'm still getting tickets with this at least weekly. I think the notes added above should help with resolving this, and I'm open to asking for further access or information from others within Intercom - just let me know what information you need to know!

**Comment by willmot** [comment]
> I think, if you don't consider this while calculating the expected backup-size, everything should be fine again? 

We should definitely account for excludes when calculating the remaining disk space.

---

We could also consider making this a warning only instead of blocking actual backups as well. If there isn't enough space then backups will obviously fail anyway.

**Comment by katmoody** [comment]
I think that makes sense @willmot - and that should at least give people a chance to get back into the settings again, which they can't do now. Do we need a new issue just for that or not?

**Comment by willmot** [comment]
Yeah let's create a new issue.

**Comment by libby-barker** [comment]
- [ ] Determine reason for why server size is coming back wrong.

**Comment by sambulance** [comment]
PR here: https://github.com/humanmade/backupwordpress/pull/1135

**Comment by katmoody** [comment]
@sambulance is this one complete then?

**Comment by sambulance** [comment]
Not sure... I made two changes relating to this ticket in 3.6.3:

1. Exclude excludes from disk size calculation, which _might_ have fixed it, but the tickets suggest there is another miscalculation somewhere.
2. Disk size too low is no longer a blocker, just a warning message. Backups will fail if disk size is actually too low.

Let's close this, and if we get any new reports let's open a new ticket and reference this one.
